//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.SOAPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WcfService.CompositeType GetDataUsingDataContract(WcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfService.CompositeType> GetDataUsingDataContractAsync(WcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBicycles", ReplyAction="http://tempuri.org/IService1/GetBicyclesResponse")]
        ApplicationService.DTOs.BicycleDTO[] GetBicycles(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBicycles", ReplyAction="http://tempuri.org/IService1/GetBicyclesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BicycleDTO[]> GetBicyclesAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBicycle", ReplyAction="http://tempuri.org/IService1/PostBicycleResponse")]
        string PostBicycle(ApplicationService.DTOs.BicycleDTO bicycleDTOs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBicycle", ReplyAction="http://tempuri.org/IService1/PostBicycleResponse")]
        System.Threading.Tasks.Task<string> PostBicycleAsync(ApplicationService.DTOs.BicycleDTO bicycleDTOs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBicycleById", ReplyAction="http://tempuri.org/IService1/GetBicycleByIdResponse")]
        ApplicationService.DTOs.BicycleDTO GetBicycleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBicycleById", ReplyAction="http://tempuri.org/IService1/GetBicycleByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BicycleDTO> GetBicycleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBicycle", ReplyAction="http://tempuri.org/IService1/DeleteBicycleResponse")]
        string DeleteBicycle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBicycle", ReplyAction="http://tempuri.org/IService1/DeleteBicycleResponse")]
        System.Threading.Tasks.Task<string> DeleteBicycleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuyers", ReplyAction="http://tempuri.org/IService1/GetBuyersResponse")]
        ApplicationService.DTOs.BuyerDTO[] GetBuyers(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuyers", ReplyAction="http://tempuri.org/IService1/GetBuyersResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BuyerDTO[]> GetBuyersAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBuyer", ReplyAction="http://tempuri.org/IService1/PostBuyerResponse")]
        string PostBuyer(ApplicationService.DTOs.BuyerDTO buyerDTOs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBuyer", ReplyAction="http://tempuri.org/IService1/PostBuyerResponse")]
        System.Threading.Tasks.Task<string> PostBuyerAsync(ApplicationService.DTOs.BuyerDTO buyerDTOs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuyerById", ReplyAction="http://tempuri.org/IService1/GetBuyerByIdResponse")]
        ApplicationService.DTOs.BuyerDTO GetBuyerById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuyerById", ReplyAction="http://tempuri.org/IService1/GetBuyerByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BuyerDTO> GetBuyerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBuyer", ReplyAction="http://tempuri.org/IService1/DeleteBuyerResponse")]
        string DeleteBuyer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBuyer", ReplyAction="http://tempuri.org/IService1/DeleteBuyerResponse")]
        System.Threading.Tasks.Task<string> DeleteBuyerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        ApplicationService.DTOs.OrderDTO[] GetOrders(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.OrderDTO[]> GetOrdersAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostOrder", ReplyAction="http://tempuri.org/IService1/PostOrderResponse")]
        string PostOrder(ApplicationService.DTOs.OrderDTO orderDTOs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostOrder", ReplyAction="http://tempuri.org/IService1/PostOrderResponse")]
        System.Threading.Tasks.Task<string> PostOrderAsync(ApplicationService.DTOs.OrderDTO orderDTOs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderById", ReplyAction="http://tempuri.org/IService1/GetOrderByIdResponse")]
        ApplicationService.DTOs.OrderDTO GetOrderById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderById", ReplyAction="http://tempuri.org/IService1/GetOrderByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.OrderDTO> GetOrderByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        string DeleteOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task<string> DeleteOrderAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVC.SOAPService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVC.SOAPService.IService1>, MVC.SOAPService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfService.CompositeType GetDataUsingDataContract(WcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfService.CompositeType> GetDataUsingDataContractAsync(WcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ApplicationService.DTOs.BicycleDTO[] GetBicycles(string query) {
            return base.Channel.GetBicycles(query);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BicycleDTO[]> GetBicyclesAsync(string query) {
            return base.Channel.GetBicyclesAsync(query);
        }
        
        public string PostBicycle(ApplicationService.DTOs.BicycleDTO bicycleDTOs) {
            return base.Channel.PostBicycle(bicycleDTOs);
        }
        
        public System.Threading.Tasks.Task<string> PostBicycleAsync(ApplicationService.DTOs.BicycleDTO bicycleDTOs) {
            return base.Channel.PostBicycleAsync(bicycleDTOs);
        }
        
        public ApplicationService.DTOs.BicycleDTO GetBicycleById(int id) {
            return base.Channel.GetBicycleById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BicycleDTO> GetBicycleByIdAsync(int id) {
            return base.Channel.GetBicycleByIdAsync(id);
        }
        
        public string DeleteBicycle(int id) {
            return base.Channel.DeleteBicycle(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBicycleAsync(int id) {
            return base.Channel.DeleteBicycleAsync(id);
        }
        
        public ApplicationService.DTOs.BuyerDTO[] GetBuyers(string query) {
            return base.Channel.GetBuyers(query);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BuyerDTO[]> GetBuyersAsync(string query) {
            return base.Channel.GetBuyersAsync(query);
        }
        
        public string PostBuyer(ApplicationService.DTOs.BuyerDTO buyerDTOs) {
            return base.Channel.PostBuyer(buyerDTOs);
        }
        
        public System.Threading.Tasks.Task<string> PostBuyerAsync(ApplicationService.DTOs.BuyerDTO buyerDTOs) {
            return base.Channel.PostBuyerAsync(buyerDTOs);
        }
        
        public ApplicationService.DTOs.BuyerDTO GetBuyerById(int id) {
            return base.Channel.GetBuyerById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BuyerDTO> GetBuyerByIdAsync(int id) {
            return base.Channel.GetBuyerByIdAsync(id);
        }
        
        public string DeleteBuyer(int id) {
            return base.Channel.DeleteBuyer(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBuyerAsync(int id) {
            return base.Channel.DeleteBuyerAsync(id);
        }
        
        public ApplicationService.DTOs.OrderDTO[] GetOrders(string query) {
            return base.Channel.GetOrders(query);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.OrderDTO[]> GetOrdersAsync(string query) {
            return base.Channel.GetOrdersAsync(query);
        }
        
        public string PostOrder(ApplicationService.DTOs.OrderDTO orderDTOs) {
            return base.Channel.PostOrder(orderDTOs);
        }
        
        public System.Threading.Tasks.Task<string> PostOrderAsync(ApplicationService.DTOs.OrderDTO orderDTOs) {
            return base.Channel.PostOrderAsync(orderDTOs);
        }
        
        public ApplicationService.DTOs.OrderDTO GetOrderById(int id) {
            return base.Channel.GetOrderById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.OrderDTO> GetOrderByIdAsync(int id) {
            return base.Channel.GetOrderByIdAsync(id);
        }
        
        public string DeleteOrder(int id) {
            return base.Channel.DeleteOrder(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteOrderAsync(int id) {
            return base.Channel.DeleteOrderAsync(id);
        }
    }
}
